/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MenuController;
import javax.swing.JOptionPane;

/**
 *
 * @author evelin_oliarski
 */
public class TelaMenu extends javax.swing.JFrame {

    private final MenuController controller; // cria controlador final.

    public TelaMenu() {
    initComponents();
    this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); 
    this.controller = new MenuController(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoMenu = new javax.swing.JLabel();
        menuOpcoes = new javax.swing.JMenuBar();
        menuOpcaoCadastros = new javax.swing.JMenu();
        cadastroCliente = new javax.swing.JMenuItem();
        cadastroFuncionario = new javax.swing.JMenuItem();
        menuOpcaoOperação = new javax.swing.JMenu();
        Agendamento = new javax.swing.JMenuItem();
        Registro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/menuImagem.jpg"))); // NOI18N
        getContentPane().add(fundoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 400, 1000));

        menuOpcaoCadastros.setText("Cadastros");

        cadastroCliente.setText("Cliente");
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteActionPerformed(evt);
            }
        });
        menuOpcaoCadastros.add(cadastroCliente);

        cadastroFuncionario.setText("Funcionário");
        cadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroFuncionarioActionPerformed(evt);
            }
        });
        menuOpcaoCadastros.add(cadastroFuncionario);

        menuOpcoes.add(menuOpcaoCadastros);

        menuOpcaoOperação.setText("Operações");
        menuOpcaoOperação.setToolTipText("");

        Agendamento.setText("Agendamento");
        Agendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendamentoActionPerformed(evt);
            }
        });
        menuOpcaoOperação.add(Agendamento);

        Registro.setText("Serviços");
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });
        menuOpcaoOperação.add(Registro);

        menuOpcoes.add(menuOpcaoOperação);

        setJMenuBar(menuOpcoes);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroFuncionarioActionPerformed
        this.controller.IrParaCadastroFuncionario();
    }//GEN-LAST:event_cadastroFuncionarioActionPerformed

    private void cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteActionPerformed
        this.controller.irParaCadastroCliente();
    }//GEN-LAST:event_cadastroClienteActionPerformed

    private void AgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendamentoActionPerformed
        this.controller.irParaAgendamento();
    }//GEN-LAST:event_AgendamentoActionPerformed

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        //inserir um de registros para apresentar dados e dias marcados 
        this.controller.IrParaServicos();
    }//GEN-LAST:event_RegistroActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja sair do sistema?", "Atenção!", JOptionPane.YES_OPTION);
        //Pergunta se o usuário realmente desejar sair do programa
        if(opcao == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Sistema finalizado!");
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agendamento;
    private javax.swing.JMenuItem Registro;
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroFuncionario;
    private javax.swing.JLabel fundoMenu;
    private javax.swing.JMenu menuOpcaoCadastros;
    private javax.swing.JMenu menuOpcaoOperação;
    private javax.swing.JMenuBar menuOpcoes;
    // End of variables declaration//GEN-END:variables
}
