
package View;

import Controller.ClienteController;
import Controller.FuncionarioController;
import DAO.ClasseConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class TelaCadastroCliente extends javax.swing.JFrame {
Connection conexao = null;
PreparedStatement pst = null;
ResultSet rs = null;

private final ClienteController controller ;
    public TelaCadastroCliente() {
        initComponents();
         controller = new ClienteController(this);
    }
    
     private void cadastrarClientes() {
        String sql = "insert into clientes(nomeClientes,emailClientes,telefoneCliente,dataNascimentoCliente,sexoCliente,enderecoCliente,cepCliente,cpfCliente) values(?,?,?,?,?,?,?,?)";
        conexao = new ClasseConexao().conectorBD();
        
        try {
            //prepara e pega os dados do cadastro
            pst = conexao.prepareStatement(sql);
            pst.setString(1, nomeCliente.getText());//nome
            pst.setString(2, sexoCliente.getSelectedItem().toString());//sexo
            pst.setString(3, cpfCliente.getText());//cpf

            //converter data dd/MM/yyyy para yyyy/MM/dd
            String dia = dataDeNascimentoCliente.getText().substring(0, 2);
            String mes = dataDeNascimentoCliente.getText().substring(3, 5);
            String ano = dataDeNascimentoCliente.getText().substring(6);
            String dataNascConv = ano + "-" + mes + "-" + dia;

            pst.setString(4, dataNascConv);//dataNascimento
            pst.setString(5, enderecoCliente.getText());//endereco
            pst.setString(6, emailCliente.getText());//email
            pst.setString(7, telefoneCliente.getText());//telefone
            pst.setString(8, cepCliente.getText());//cep

            //validacao dos campos obrigatorios
            if (nomeCliente.getText().isEmpty() || cpfCliente.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha Todos os Campos Obrigatorios");
            } else {

                //atualiza a tabela cliente com os dados do formulario
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Cliente Cadastrado Com Sucesso");

                    nomeCliente.setText(null);//nome
                    cpfCliente.setText(null);//cpf
                    dataDeNascimentoCliente.setText(null);//dataNascimento
                    enderecoCliente.setText(null);//endereco
                    emailCliente.setText(null);//email
                    telefoneCliente.setText(null);//telefone
                    cepCliente.setText(null);//cep
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeCliente = new javax.swing.JTextField();
        dataDeNascimentoCliente = new javax.swing.JTextField();
        cpfCliente = new javax.swing.JTextField();
        telefoneCliente = new javax.swing.JTextField();
        enderecoCliente = new javax.swing.JTextField();
        sexoCliente = new javax.swing.JComboBox<>();
        cepCliente = new javax.swing.JTextField();
        emailCliente = new javax.swing.JTextField();
        confirmarCliente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        fundoCadastroCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeCliente.setBackground(new java.awt.Color(204, 204, 204));
        nomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeClienteActionPerformed(evt);
            }
        });
        getContentPane().add(nomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 242, 220, 30));

        dataDeNascimentoCliente.setBackground(new java.awt.Color(204, 204, 204));
        dataDeNascimentoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDeNascimentoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(dataDeNascimentoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 220, 30));

        cpfCliente.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(cpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 462, 220, 30));

        telefoneCliente.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(telefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 532, 220, 30));

        enderecoCliente.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(enderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 672, 220, 30));

        sexoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "Feminino", "Masculino", "Outros" }));
        getContentPane().add(sexoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 312, 220, 30));

        cepCliente.setBackground(new java.awt.Color(204, 204, 204));
        cepCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepClienteActionPerformed(evt);
            }
        });
        getContentPane().add(cepCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 742, 220, 30));

        emailCliente.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(emailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 602, 220, 30));

        confirmarCliente.setBackground(new java.awt.Color(0, 0, 0));
        confirmarCliente.setFont(new java.awt.Font("Artifakt Element Light", 0, 24)); // NOI18N
        confirmarCliente.setForeground(new java.awt.Color(255, 255, 255));
        confirmarCliente.setText("Confirmar");
        confirmarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(confirmarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 813, 260, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/botão voltar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 50));

        fundoCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/cadastroClienteImagem.png"))); // NOI18N
        getContentPane().add(fundoCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cepClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepClienteActionPerformed
        // Recebe o CEP do cliente
    }//GEN-LAST:event_cepClienteActionPerformed

    private void nomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeClienteActionPerformed
        // Recebe nome do cliente
    }//GEN-LAST:event_nomeClienteActionPerformed

    private void dataDeNascimentoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDeNascimentoClienteActionPerformed
        //Recebe data de nascimento do cliente
    }//GEN-LAST:event_dataDeNascimentoClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.controller.voltarMenu();// Volta para o menu inicial 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarClienteActionPerformed
     cadastrarClientes();
    }//GEN-LAST:event_confirmarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cepCliente;
    private javax.swing.JButton confirmarCliente;
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JTextField dataDeNascimentoCliente;
    private javax.swing.JTextField emailCliente;
    private javax.swing.JTextField enderecoCliente;
    private javax.swing.JLabel fundoCadastroCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JComboBox<String> sexoCliente;
    private javax.swing.JTextField telefoneCliente;
    // End of variables declaration//GEN-END:variables
}
